{% set name = "geoparse" %}
{% set version = "2.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f2185310e5f7c6bd551c763476ad8a296cf7c355afa3136881e4bad5a5dad81a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.7
    - pandas >=0.17
    - python >=3.6
    - requests >=2.21.0
    - tqdm >=4.31.1

test:
  imports:
    - GEOparse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/guma44/GEOparse
  summary: Python library to access Gene Expression Omnibus Database (GEO)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
